CREATE TABLE produtor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   primeiro_nome VARCHAR(255) NOT NULL,
   ultimo_nome VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   senha VARCHAR(255) NOT NULL,
   codigo BIGINT NOT NULL,
   nome_localidade VARCHAR(255) NOT NULL,
   municipio VARCHAR(255) NOT NULL,
   CONSTRAINT pk_produtor PRIMARY KEY (id, codigo)
);

ALTER TABLE produtor ADD CONSTRAINT uc_produtor_cpf UNIQUE (cpf);

ALTER TABLE produtor ADD CONSTRAINT uc_produtor_email UNIQUE (email);